// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateCodexAccount(arg1) {
  return window['go']['main']['DesktopAgentApp']['ActivateCodexAccount'](arg1);
}

export function ActivateGitHubAccount(arg1) {
  return window['go']['main']['DesktopAgentApp']['ActivateGitHubAccount'](arg1);
}

export function ActivateProject(arg1) {
  return window['go']['main']['DesktopAgentApp']['ActivateProject'](arg1);
}

export function ActivateProviderProfile(arg1) {
  return window['go']['main']['DesktopAgentApp']['ActivateProviderProfile'](arg1);
}

export function ApproveRemoteConnectionRequest(arg1) {
  return window['go']['main']['DesktopAgentApp']['ApproveRemoteConnectionRequest'](arg1);
}

export function BindSessionProject(arg1) {
  return window['go']['main']['DesktopAgentApp']['BindSessionProject'](arg1);
}

export function BlockRemoteConnectionRequest(arg1) {
  return window['go']['main']['DesktopAgentApp']['BlockRemoteConnectionRequest'](arg1);
}

export function Bootstrap() {
  return window['go']['main']['DesktopAgentApp']['Bootstrap']();
}

export function BrowseProjectEntries(arg1, arg2) {
  return window['go']['main']['DesktopAgentApp']['BrowseProjectEntries'](arg1, arg2);
}

export function CancelBuiltinVisionModelInstall() {
  return window['go']['main']['DesktopAgentApp']['CancelBuiltinVisionModelInstall']();
}

export function CancelImageGeneration(arg1) {
  return window['go']['main']['DesktopAgentApp']['CancelImageGeneration'](arg1);
}

export function CancelProviderImport(arg1) {
  return window['go']['main']['DesktopAgentApp']['CancelProviderImport'](arg1);
}

export function CancelRun(arg1) {
  return window['go']['main']['DesktopAgentApp']['CancelRun'](arg1);
}

export function CancelSubagentJob(arg1) {
  return window['go']['main']['DesktopAgentApp']['CancelSubagentJob'](arg1);
}

export function CheckDesktopUpdate() {
  return window['go']['main']['DesktopAgentApp']['CheckDesktopUpdate']();
}

export function ClearProjectAudit(arg1) {
  return window['go']['main']['DesktopAgentApp']['ClearProjectAudit'](arg1);
}

export function ClearRemoteNodePairing() {
  return window['go']['main']['DesktopAgentApp']['ClearRemoteNodePairing']();
}

export function ClearRemoteSecurityPassword() {
  return window['go']['main']['DesktopAgentApp']['ClearRemoteSecurityPassword']();
}

export function ClearSessionGoal(arg1) {
  return window['go']['main']['DesktopAgentApp']['ClearSessionGoal'](arg1);
}

export function ClearWorkspaceChanges() {
  return window['go']['main']['DesktopAgentApp']['ClearWorkspaceChanges']();
}

export function CloseProject() {
  return window['go']['main']['DesktopAgentApp']['CloseProject']();
}

export function CloseWorkbenchTerminalSession(arg1) {
  return window['go']['main']['DesktopAgentApp']['CloseWorkbenchTerminalSession'](arg1);
}

export function CompleteSessionGoal(arg1) {
  return window['go']['main']['DesktopAgentApp']['CompleteSessionGoal'](arg1);
}

export function CompressSession(arg1) {
  return window['go']['main']['DesktopAgentApp']['CompressSession'](arg1);
}

export function ConfirmProviderImport(arg1) {
  return window['go']['main']['DesktopAgentApp']['ConfirmProviderImport'](arg1);
}

export function ConnectMCPServers() {
  return window['go']['main']['DesktopAgentApp']['ConnectMCPServers']();
}

export function CopySavedWorkflowExternalCommand(arg1) {
  return window['go']['main']['DesktopAgentApp']['CopySavedWorkflowExternalCommand'](arg1);
}

export function CreateCodexAccount(arg1) {
  return window['go']['main']['DesktopAgentApp']['CreateCodexAccount'](arg1);
}

export function CreateGitHubAccount(arg1) {
  return window['go']['main']['DesktopAgentApp']['CreateGitHubAccount'](arg1);
}

export function CreateManualBackup() {
  return window['go']['main']['DesktopAgentApp']['CreateManualBackup']();
}

export function CreateProject(arg1) {
  return window['go']['main']['DesktopAgentApp']['CreateProject'](arg1);
}

export function CreateSession() {
  return window['go']['main']['DesktopAgentApp']['CreateSession']();
}

export function DeleteBuiltinVisionModel(arg1) {
  return window['go']['main']['DesktopAgentApp']['DeleteBuiltinVisionModel'](arg1);
}

export function DeleteSavedWorkflow(arg1) {
  return window['go']['main']['DesktopAgentApp']['DeleteSavedWorkflow'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['main']['DesktopAgentApp']['DeleteSession'](arg1);
}

export function DiscardChatImage(arg1) {
  return window['go']['main']['DesktopAgentApp']['DiscardChatImage'](arg1);
}

export function DiscoverRemoteADBDevices() {
  return window['go']['main']['DesktopAgentApp']['DiscoverRemoteADBDevices']();
}

export function DiscoverRemoteDevices() {
  return window['go']['main']['DesktopAgentApp']['DiscoverRemoteDevices']();
}

export function DismissWorkflowPlan(arg1) {
  return window['go']['main']['DesktopAgentApp']['DismissWorkflowPlan'](arg1);
}

export function ExecuteWorkflowPlan(arg1) {
  return window['go']['main']['DesktopAgentApp']['ExecuteWorkflowPlan'](arg1);
}

export function ExportProjectAudit(arg1) {
  return window['go']['main']['DesktopAgentApp']['ExportProjectAudit'](arg1);
}

export function ExportSession(arg1) {
  return window['go']['main']['DesktopAgentApp']['ExportSession'](arg1);
}

export function FetchProviderModels(arg1) {
  return window['go']['main']['DesktopAgentApp']['FetchProviderModels'](arg1);
}

export function ForgetRecentProject(arg1) {
  return window['go']['main']['DesktopAgentApp']['ForgetRecentProject'](arg1);
}

export function ForkSession(arg1) {
  return window['go']['main']['DesktopAgentApp']['ForkSession'](arg1);
}

export function GenerateImage(arg1) {
  return window['go']['main']['DesktopAgentApp']['GenerateImage'](arg1);
}

export function GetBackupStatus() {
  return window['go']['main']['DesktopAgentApp']['GetBackupStatus']();
}

export function GetBuiltinVisionModelStatus() {
  return window['go']['main']['DesktopAgentApp']['GetBuiltinVisionModelStatus']();
}

export function GetChatImageDataURL(arg1) {
  return window['go']['main']['DesktopAgentApp']['GetChatImageDataURL'](arg1);
}

export function GetCodexAccountPool() {
  return window['go']['main']['DesktopAgentApp']['GetCodexAccountPool']();
}

export function GetComposerCatalog() {
  return window['go']['main']['DesktopAgentApp']['GetComposerCatalog']();
}

export function GetMCPState() {
  return window['go']['main']['DesktopAgentApp']['GetMCPState']();
}

export function GetPendingProviderImport() {
  return window['go']['main']['DesktopAgentApp']['GetPendingProviderImport']();
}

export function GetProjectAudit(arg1) {
  return window['go']['main']['DesktopAgentApp']['GetProjectAudit'](arg1);
}

export function GetProjectKnowledge() {
  return window['go']['main']['DesktopAgentApp']['GetProjectKnowledge']();
}

export function GetProjectToolPreferences() {
  return window['go']['main']['DesktopAgentApp']['GetProjectToolPreferences']();
}

export function GetProviderImportProtocolState() {
  return window['go']['main']['DesktopAgentApp']['GetProviderImportProtocolState']();
}

export function GetProviderUsageState() {
  return window['go']['main']['DesktopAgentApp']['GetProviderUsageState']();
}

export function GetSavedWorkflowExternalCommand(arg1) {
  return window['go']['main']['DesktopAgentApp']['GetSavedWorkflowExternalCommand'](arg1);
}

export function GetSavedWorkflowState() {
  return window['go']['main']['DesktopAgentApp']['GetSavedWorkflowState']();
}

export function GetSession(arg1) {
  return window['go']['main']['DesktopAgentApp']['GetSession'](arg1);
}

export function GetSessionStats(arg1) {
  return window['go']['main']['DesktopAgentApp']['GetSessionStats'](arg1);
}

export function GetWorkbenchGit() {
  return window['go']['main']['DesktopAgentApp']['GetWorkbenchGit']();
}

export function GetWorkspaceChanges() {
  return window['go']['main']['DesktopAgentApp']['GetWorkspaceChanges']();
}

export function GetWorkspaceDiff(arg1) {
  return window['go']['main']['DesktopAgentApp']['GetWorkspaceDiff'](arg1);
}

export function GetWorkspaceReviewDiff(arg1, arg2) {
  return window['go']['main']['DesktopAgentApp']['GetWorkspaceReviewDiff'](arg1, arg2);
}

export function HideMainWindow() {
  return window['go']['main']['DesktopAgentApp']['HideMainWindow']();
}

export function ImportSession() {
  return window['go']['main']['DesktopAgentApp']['ImportSession']();
}

export function ListWorkbenchFiles(arg1) {
  return window['go']['main']['DesktopAgentApp']['ListWorkbenchFiles'](arg1);
}

export function OpenDesktopUpdateDownload() {
  return window['go']['main']['DesktopAgentApp']['OpenDesktopUpdateDownload']();
}

export function OpenProject() {
  return window['go']['main']['DesktopAgentApp']['OpenProject']();
}

export function PendingAsk(arg1) {
  return window['go']['main']['DesktopAgentApp']['PendingAsk'](arg1);
}

export function PullCredentialsFromPhone(arg1) {
  return window['go']['main']['DesktopAgentApp']['PullCredentialsFromPhone'](arg1);
}

export function PushCredentialsToPhone(arg1) {
  return window['go']['main']['DesktopAgentApp']['PushCredentialsToPhone'](arg1);
}

export function ReadWorkbenchAsset(arg1) {
  return window['go']['main']['DesktopAgentApp']['ReadWorkbenchAsset'](arg1);
}

export function ReadWorkbenchFile(arg1) {
  return window['go']['main']['DesktopAgentApp']['ReadWorkbenchFile'](arg1);
}

export function ReclaimSessionExecution(arg1) {
  return window['go']['main']['DesktopAgentApp']['ReclaimSessionExecution'](arg1);
}

export function RefreshCodexStatus(arg1) {
  return window['go']['main']['DesktopAgentApp']['RefreshCodexStatus'](arg1);
}

export function RefreshProviderUsage(arg1) {
  return window['go']['main']['DesktopAgentApp']['RefreshProviderUsage'](arg1);
}

export function RejectRemoteConnectionRequest(arg1) {
  return window['go']['main']['DesktopAgentApp']['RejectRemoteConnectionRequest'](arg1);
}

export function RemoveCodexAccount(arg1) {
  return window['go']['main']['DesktopAgentApp']['RemoveCodexAccount'](arg1);
}

export function RemoveGitHubAccount(arg1) {
  return window['go']['main']['DesktopAgentApp']['RemoveGitHubAccount'](arg1);
}

export function RenameSession(arg1) {
  return window['go']['main']['DesktopAgentApp']['RenameSession'](arg1);
}

export function ResizeWorkbenchTerminalSession(arg1) {
  return window['go']['main']['DesktopAgentApp']['ResizeWorkbenchTerminalSession'](arg1);
}

export function ResolveApproval(arg1) {
  return window['go']['main']['DesktopAgentApp']['ResolveApproval'](arg1);
}

export function ResolveAsk(arg1) {
  return window['go']['main']['DesktopAgentApp']['ResolveAsk'](arg1);
}

export function RestoreBackup(arg1) {
  return window['go']['main']['DesktopAgentApp']['RestoreBackup'](arg1);
}

export function RevealWorkbenchPath(arg1) {
  return window['go']['main']['DesktopAgentApp']['RevealWorkbenchPath'](arg1);
}

export function RollbackSession(arg1) {
  return window['go']['main']['DesktopAgentApp']['RollbackSession'](arg1);
}

export function RotateRemoteTemporaryCode() {
  return window['go']['main']['DesktopAgentApp']['RotateRemoteTemporaryCode']();
}

export function RunSavedWorkflowNow(arg1) {
  return window['go']['main']['DesktopAgentApp']['RunSavedWorkflowNow'](arg1);
}

export function SaveGitHubConfig(arg1) {
  return window['go']['main']['DesktopAgentApp']['SaveGitHubConfig'](arg1);
}

export function SaveKnowledgeLibrary(arg1) {
  return window['go']['main']['DesktopAgentApp']['SaveKnowledgeLibrary'](arg1);
}

export function SaveMCPServers(arg1) {
  return window['go']['main']['DesktopAgentApp']['SaveMCPServers'](arg1);
}

export function SaveProjectKnowledgeLibrary(arg1) {
  return window['go']['main']['DesktopAgentApp']['SaveProjectKnowledgeLibrary'](arg1);
}

export function SaveRemoteNodeConfig(arg1) {
  return window['go']['main']['DesktopAgentApp']['SaveRemoteNodeConfig'](arg1);
}

export function SaveSavedWorkflow(arg1) {
  return window['go']['main']['DesktopAgentApp']['SaveSavedWorkflow'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['DesktopAgentApp']['SaveSettings'](arg1);
}

export function SaveWorkbenchFile(arg1) {
  return window['go']['main']['DesktopAgentApp']['SaveWorkbenchFile'](arg1);
}

export function SearchProjectEntries(arg1) {
  return window['go']['main']['DesktopAgentApp']['SearchProjectEntries'](arg1);
}

export function SelectBackupForRestore() {
  return window['go']['main']['DesktopAgentApp']['SelectBackupForRestore']();
}

export function SelectBuiltinVisionModel(arg1) {
  return window['go']['main']['DesktopAgentApp']['SelectBuiltinVisionModel'](arg1);
}

export function SelectChatImages() {
  return window['go']['main']['DesktopAgentApp']['SelectChatImages']();
}

export function SelectProject() {
  return window['go']['main']['DesktopAgentApp']['SelectProject']();
}

export function SelectProjectParent(arg1) {
  return window['go']['main']['DesktopAgentApp']['SelectProjectParent'](arg1);
}

export function SelectRemoteWorkspace(arg1) {
  return window['go']['main']['DesktopAgentApp']['SelectRemoteWorkspace'](arg1);
}

export function SelectSession(arg1) {
  return window['go']['main']['DesktopAgentApp']['SelectSession'](arg1);
}

export function SendMessage(arg1) {
  return window['go']['main']['DesktopAgentApp']['SendMessage'](arg1);
}

export function SetCCSwitchProtocolCompatibility(arg1) {
  return window['go']['main']['DesktopAgentApp']['SetCCSwitchProtocolCompatibility'](arg1);
}

export function SetProviderModel(arg1) {
  return window['go']['main']['DesktopAgentApp']['SetProviderModel'](arg1);
}

export function SetProviderReasoningEffort(arg1) {
  return window['go']['main']['DesktopAgentApp']['SetProviderReasoningEffort'](arg1);
}

export function SetRemoteDoNotDisturb(arg1) {
  return window['go']['main']['DesktopAgentApp']['SetRemoteDoNotDisturb'](arg1);
}

export function SetRemoteSecurityPassword(arg1) {
  return window['go']['main']['DesktopAgentApp']['SetRemoteSecurityPassword'](arg1);
}

export function SetSessionCodexAccountPinned(arg1) {
  return window['go']['main']['DesktopAgentApp']['SetSessionCodexAccountPinned'](arg1);
}

export function SetSessionCompressionActive(arg1) {
  return window['go']['main']['DesktopAgentApp']['SetSessionCompressionActive'](arg1);
}

export function SetSessionGoalStatus(arg1) {
  return window['go']['main']['DesktopAgentApp']['SetSessionGoalStatus'](arg1);
}

export function SetSessionPlanMode(arg1, arg2) {
  return window['go']['main']['DesktopAgentApp']['SetSessionPlanMode'](arg1, arg2);
}

export function StartBuiltinVisionModelInstall(arg1) {
  return window['go']['main']['DesktopAgentApp']['StartBuiltinVisionModelInstall'](arg1);
}

export function StartCodexDeviceLogin(arg1) {
  return window['go']['main']['DesktopAgentApp']['StartCodexDeviceLogin'](arg1);
}

export function StartRemoteNode(arg1) {
  return window['go']['main']['DesktopAgentApp']['StartRemoteNode'](arg1);
}

export function StartWorkbenchTerminalSession(arg1) {
  return window['go']['main']['DesktopAgentApp']['StartWorkbenchTerminalSession'](arg1);
}

export function StopRemoteNode() {
  return window['go']['main']['DesktopAgentApp']['StopRemoteNode']();
}

export function TestGitHubConnection() {
  return window['go']['main']['DesktopAgentApp']['TestGitHubConnection']();
}

export function UnblockRemotePeer(arg1) {
  return window['go']['main']['DesktopAgentApp']['UnblockRemotePeer'](arg1);
}

export function UndoWorkspaceReview(arg1) {
  return window['go']['main']['DesktopAgentApp']['UndoWorkspaceReview'](arg1);
}

export function UpdateBackupSettings(arg1) {
  return window['go']['main']['DesktopAgentApp']['UpdateBackupSettings'](arg1);
}

export function UpdateCodexAccount(arg1) {
  return window['go']['main']['DesktopAgentApp']['UpdateCodexAccount'](arg1);
}

export function UpdateCodexAccountPoolSettings(arg1) {
  return window['go']['main']['DesktopAgentApp']['UpdateCodexAccountPoolSettings'](arg1);
}

export function UpscaleImage4K(arg1) {
  return window['go']['main']['DesktopAgentApp']['UpscaleImage4K'](arg1);
}

export function VoiceInstallAsrModel() {
  return window['go']['main']['DesktopAgentApp']['VoiceInstallAsrModel']();
}

export function VoiceInstallRuntime() {
  return window['go']['main']['DesktopAgentApp']['VoiceInstallRuntime']();
}

export function VoiceInstallTtsModel() {
  return window['go']['main']['DesktopAgentApp']['VoiceInstallTtsModel']();
}

export function VoiceSpeak(arg1, arg2) {
  return window['go']['main']['DesktopAgentApp']['VoiceSpeak'](arg1, arg2);
}

export function VoiceStartListening() {
  return window['go']['main']['DesktopAgentApp']['VoiceStartListening']();
}

export function VoiceStartRecording() {
  return window['go']['main']['DesktopAgentApp']['VoiceStartRecording']();
}

export function VoiceStatus() {
  return window['go']['main']['DesktopAgentApp']['VoiceStatus']();
}

export function VoiceStopListeningAndGetFinal() {
  return window['go']['main']['DesktopAgentApp']['VoiceStopListeningAndGetFinal']();
}

export function VoiceStopRecordingAndRecognize() {
  return window['go']['main']['DesktopAgentApp']['VoiceStopRecordingAndRecognize']();
}

export function VoiceStopSpeaking() {
  return window['go']['main']['DesktopAgentApp']['VoiceStopSpeaking']();
}

export function WriteWorkbenchTerminalSession(arg1) {
  return window['go']['main']['DesktopAgentApp']['WriteWorkbenchTerminalSession'](arg1);
}
