// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {desktopbridge} from '../models';

export function ActivateCodexAccount(arg1:main.CodexAccountRuntimeRequest):Promise<main.CodexRuntimeStatus>;

export function ActivateGitHubAccount(arg1:main.GitHubAccountRequest):Promise<main.SavedWorkflowState>;

export function ActivateProject(arg1:string):Promise<main.PublicDesktopConfig>;

export function ActivateProviderProfile(arg1:string):Promise<main.PublicDesktopConfig>;

export function ApproveRemoteConnectionRequest(arg1:string):Promise<desktopbridge.RemoteNodeSnapshot>;

export function BindSessionProject(arg1:main.SessionProjectBindingRequest):Promise<main.ChatSession>;

export function BlockRemoteConnectionRequest(arg1:string):Promise<desktopbridge.RemoteNodeSnapshot>;

export function Bootstrap():Promise<main.BootstrapState>;

export function BrowseProjectEntries(arg1:string,arg2:string):Promise<Array<main.ProjectEntry>>;

export function CancelBuiltinVisionModelInstall():Promise<void>;

export function CancelImageGeneration(arg1:string):Promise<boolean>;

export function CancelProviderImport(arg1:string):Promise<void>;

export function CancelRun(arg1:string):Promise<boolean>;

export function CancelSubagentJob(arg1:main.CancelSubagentJobRequest):Promise<main.ChatSession>;

export function CheckDesktopUpdate():Promise<main.DesktopUpdateInfo>;

export function ClearProjectAudit(arg1:boolean):Promise<main.ProjectAuditPage>;

export function ClearRemoteNodePairing():Promise<desktopbridge.RemoteNodeSnapshot>;

export function ClearRemoteSecurityPassword():Promise<desktopbridge.RemoteNodeSnapshot>;

export function ClearSessionGoal(arg1:string):Promise<main.ChatSession>;

export function ClearWorkspaceChanges():Promise<main.WorkspaceChangeState>;

export function CloseProject():Promise<main.PublicDesktopConfig>;

export function CloseWorkbenchTerminalSession(arg1:string):Promise<void>;

export function CompleteSessionGoal(arg1:string):Promise<main.ChatSession>;

export function CompressSession(arg1:string):Promise<main.ChatSession>;

export function ConfirmProviderImport(arg1:main.ConfirmProviderImportRequest):Promise<main.ProviderImportResult>;

export function ConnectMCPServers():Promise<main.MCPState>;

export function CopySavedWorkflowExternalCommand(arg1:string):Promise<void>;

export function CreateCodexAccount(arg1:main.CodexAccountRuntimeRequest):Promise<main.CodexRuntimeStatus>;

export function CreateGitHubAccount(arg1:main.GitHubAccountRequest):Promise<main.SavedWorkflowState>;

export function CreateManualBackup():Promise<main.DesktopBackupOperationResult>;

export function CreateProject(arg1:main.CreateProjectRequest):Promise<main.PublicDesktopConfig>;

export function CreateSession():Promise<main.ChatSession>;

export function DeleteBuiltinVisionModel(arg1:string):Promise<void>;

export function DeleteSavedWorkflow(arg1:string):Promise<main.SavedWorkflowState>;

export function DeleteSession(arg1:string):Promise<void>;

export function DiscardChatImage(arg1:main.DiscardChatImageRequest):Promise<void>;

export function DiscoverRemoteADBDevices():Promise<Array<desktopbridge.RemoteADBDevice>>;

export function DiscoverRemoteDevices():Promise<Array<desktopbridge.RemoteDiscoveredDevice>>;

export function DismissWorkflowPlan(arg1:string):Promise<main.ChatSession>;

export function ExecuteWorkflowPlan(arg1:string):Promise<void>;

export function ExportProjectAudit(arg1:string):Promise<main.ProjectAuditExportResult>;

export function ExportSession(arg1:main.ExportSessionRequest):Promise<string>;

export function FetchProviderModels(arg1:main.ProviderModelCatalogRequest):Promise<main.ProviderModelCatalogResult>;

export function ForgetRecentProject(arg1:string):Promise<main.PublicDesktopConfig>;

export function ForkSession(arg1:main.SessionPointRequest):Promise<main.ChatSession>;

export function GenerateImage(arg1:main.GenerateImageRequest):Promise<void>;

export function GetBackupStatus():Promise<main.DesktopBackupStatus>;

export function GetBuiltinVisionModelStatus():Promise<main.BuiltinVisionModelStatus>;

export function GetChatImageDataURL(arg1:main.ChatImagePreviewRequest):Promise<string>;

export function GetCodexAccountPool():Promise<main.CodexAccountPoolState>;

export function GetComposerCatalog():Promise<main.ComposerCatalog>;

export function GetMCPState():Promise<main.MCPState>;

export function GetPendingProviderImport():Promise<main.ProviderImportPreview>;

export function GetProjectAudit(arg1:main.ProjectAuditQuery):Promise<main.ProjectAuditPage>;

export function GetProjectKnowledge():Promise<main.ProjectKnowledgeSnapshot>;

export function GetProjectToolPreferences():Promise<main.ProjectToolPreferencesSnapshot>;

export function GetProviderImportProtocolState():Promise<main.ProviderImportProtocolState>;

export function GetProviderUsageState():Promise<main.ProviderUsageState>;

export function GetSavedWorkflowExternalCommand(arg1:string):Promise<string>;

export function GetSavedWorkflowState():Promise<main.SavedWorkflowState>;

export function GetSession(arg1:string):Promise<main.ChatSession>;

export function GetSessionStats(arg1:string):Promise<main.SessionStats>;

export function GetWorkbenchGit():Promise<main.WorkbenchGitSnapshot>;

export function GetWorkspaceChanges():Promise<main.WorkspaceChangeState>;

export function GetWorkspaceDiff(arg1:string):Promise<main.WorkspaceDiff>;

export function GetWorkspaceReviewDiff(arg1:string,arg2:string):Promise<main.WorkspaceDiff>;

export function HideMainWindow():Promise<void>;

export function ImportSession():Promise<main.ChatSession>;

export function ListWorkbenchFiles(arg1:string):Promise<Array<main.WorkbenchFileEntry>>;

export function OpenDesktopUpdateDownload():Promise<void>;

export function OpenProject():Promise<main.PublicDesktopConfig>;

export function PendingAsk(arg1:string):Promise<main.AskRequest>;

export function PullCredentialsFromPhone(arg1:main.SyncCredentialsRequest):Promise<main.SyncCredentialsOperationResult>;

export function PushCredentialsToPhone(arg1:main.SyncCredentialsRequest):Promise<main.SyncCredentialsOperationResult>;

export function ReadWorkbenchAsset(arg1:string):Promise<main.WorkbenchFileAsset>;

export function ReadWorkbenchFile(arg1:string):Promise<main.WorkbenchFileDocument>;

export function ReclaimSessionExecution(arg1:string):Promise<main.ChatSession>;

export function RefreshCodexStatus(arg1:main.CodexRuntimeRequest):Promise<main.CodexRuntimeStatus>;

export function RefreshProviderUsage(arg1:string):Promise<main.ProviderUsageState>;

export function RejectRemoteConnectionRequest(arg1:string):Promise<desktopbridge.RemoteNodeSnapshot>;

export function RemoveCodexAccount(arg1:main.CodexAccountRuntimeRequest):Promise<main.CodexRuntimeStatus>;

export function RemoveGitHubAccount(arg1:main.GitHubAccountRequest):Promise<main.SavedWorkflowState>;

export function RenameSession(arg1:main.RenameSessionRequest):Promise<main.ChatSession>;

export function ResizeWorkbenchTerminalSession(arg1:main.WorkbenchTerminalResizeRequest):Promise<void>;

export function ResolveApproval(arg1:main.ApprovalDecision):Promise<boolean>;

export function ResolveAsk(arg1:main.AskDecision):Promise<boolean>;

export function RestoreBackup(arg1:main.RestoreDesktopBackupRequest):Promise<main.DesktopBackupOperationResult>;

export function RevealWorkbenchPath(arg1:string):Promise<void>;

export function RollbackSession(arg1:main.SessionPointRequest):Promise<main.ChatSession>;

export function RotateRemoteTemporaryCode():Promise<desktopbridge.RemoteNodeSnapshot>;

export function RunSavedWorkflowNow(arg1:main.RunSavedWorkflowRequest):Promise<main.SavedWorkflowState>;

export function SaveGitHubConfig(arg1:main.SaveGitHubConfigRequest):Promise<main.SavedWorkflowState>;

export function SaveKnowledgeLibrary(arg1:main.KnowledgeLibrary):Promise<main.KnowledgeLibrary>;

export function SaveMCPServers(arg1:main.SaveMCPServersRequest):Promise<main.MCPState>;

export function SaveProjectKnowledgeLibrary(arg1:main.KnowledgeLibrary):Promise<main.ProjectKnowledgeSnapshot>;

export function SaveRemoteNodeConfig(arg1:desktopbridge.RemoteNodeConfig):Promise<desktopbridge.RemoteNodeSnapshot>;

export function SaveSavedWorkflow(arg1:main.SaveSavedWorkflowRequest):Promise<main.SavedWorkflowState>;

export function SaveSettings(arg1:main.SaveSettingsRequest):Promise<main.PublicDesktopConfig>;

export function SaveWorkbenchFile(arg1:main.WorkbenchSaveFileRequest):Promise<main.WorkbenchFileDocument>;

export function SearchProjectEntries(arg1:string):Promise<Array<main.ProjectEntry>>;

export function SelectBackupForRestore():Promise<main.DesktopRestoreSelection>;

export function SelectBuiltinVisionModel(arg1:string):Promise<void>;

export function SelectChatImages():Promise<Array<main.SelectedChatImage>>;

export function SelectProject():Promise<string>;

export function SelectProjectParent(arg1:string):Promise<string>;

export function SelectRemoteWorkspace(arg1:string):Promise<string>;

export function SelectSession(arg1:string):Promise<main.SessionSelection>;

export function SendMessage(arg1:main.SendMessageRequest):Promise<void>;

export function SetCCSwitchProtocolCompatibility(arg1:boolean):Promise<main.ProviderImportProtocolState>;

export function SetProviderModel(arg1:main.SetProviderModelRequest):Promise<main.PublicDesktopConfig>;

export function SetProviderReasoningEffort(arg1:main.SetProviderReasoningEffortRequest):Promise<main.PublicDesktopConfig>;

export function SetRemoteDoNotDisturb(arg1:boolean):Promise<desktopbridge.RemoteNodeSnapshot>;

export function SetRemoteSecurityPassword(arg1:string):Promise<desktopbridge.RemoteNodeSnapshot>;

export function SetSessionCodexAccountPinned(arg1:main.CodexSessionAccountPinRequest):Promise<main.ChatSession>;

export function SetSessionCompressionActive(arg1:main.SetSessionCompressionRequest):Promise<main.ChatSession>;

export function SetSessionGoalStatus(arg1:main.SetSessionGoalStatusRequest):Promise<main.ChatSession>;

export function SetSessionPlanMode(arg1:string,arg2:boolean):Promise<main.ChatSession>;

export function StartBuiltinVisionModelInstall(arg1:string):Promise<void>;

export function StartCodexDeviceLogin(arg1:main.CodexRuntimeRequest):Promise<main.CodexRuntimeStatus>;

export function StartRemoteNode(arg1:main.StartRemoteNodeRequest):Promise<desktopbridge.RemoteNodeSnapshot>;

export function StartWorkbenchTerminalSession(arg1:main.WorkbenchTerminalStartRequest):Promise<main.WorkbenchTerminalSessionInfo>;

export function StopRemoteNode():Promise<desktopbridge.RemoteNodeSnapshot>;

export function TestGitHubConnection():Promise<main.SavedWorkflowState>;

export function UnblockRemotePeer(arg1:string):Promise<desktopbridge.RemoteNodeSnapshot>;

export function UndoWorkspaceReview(arg1:string):Promise<main.ChatSession>;

export function UpdateBackupSettings(arg1:main.DesktopBackupSettings):Promise<main.DesktopBackupStatus>;

export function UpdateCodexAccount(arg1:main.CodexAccountMutationRequest):Promise<main.CodexRuntimeStatus>;

export function UpdateCodexAccountPoolSettings(arg1:main.CodexAccountPoolSettingsRequest):Promise<main.CodexRuntimeStatus>;

export function UpscaleImage4K(arg1:main.UpscaleImageRequest):Promise<void>;

export function VoiceInstallAsrModel():Promise<void>;

export function VoiceInstallRuntime():Promise<void>;

export function VoiceInstallTtsModel():Promise<void>;

export function VoiceSpeak(arg1:string,arg2:number):Promise<void>;

export function VoiceStartListening():Promise<void>;

export function VoiceStartRecording():Promise<void>;

export function VoiceStatus():Promise<main.VoiceRuntimeStatus>;

export function VoiceStopListeningAndGetFinal():Promise<string>;

export function VoiceStopRecordingAndRecognize():Promise<string>;

export function VoiceStopSpeaking():Promise<void>;

export function WriteWorkbenchTerminalSession(arg1:main.WorkbenchTerminalWriteRequest):Promise<void>;
